In [1]:
import numpy as np 

Declaring scalars, vectors, and matrices

Scalars

In [2]:
s = 5

In [3]:
s

5

Vectors

In [4]:
v = np.array([5, -2.4])
v

array([ 5. , -2.4])

Matrices

In [5]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

Data types

In [7]:
type(s)

int

In [8]:
type(v)

numpy.ndarray

In [9]:
type(m)

numpy.ndarray

Data shapes

In [10]:
m.shape

(2, 3)

In [11]:
v.shape

(2,)

In [13]:
v.reshape(1,2)

array([[ 5. , -2.4]])

In [15]:
v.reshape(2,1)

array([[ 5. ],
       [-2.4]])