In [1]:
import numpy as np 
from sklearn.model_selection import  train_test_split

In [3]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

SPLIT THE DATA

In [4]:
train_test_split(a)

[array([ 29,  87,  94,   2,  24,  20,  27,  43,  55,  91,  89,  77,  67,
         14,  32,  28,  26,  57,  37,  81,  97,  33,  56,  36,  31,  75,
         12,  59,  78, 100,  49,  76,  53,  45,   8,  40,   9,  21,  80,
         11,  19,  13,  17,   5,  51,  96,  69,   7,  52,  79,  16,  38,
         71,  47,  58,  54,  50,  93,  66,  34,  60,  99,  41,  23,  35,
         86,  25,  65,  46,  95,  62,  39,  61,  48,  82]),
 array([18, 85, 98, 42,  3, 84, 10,  4, 72, 73,  6, 83, 15, 68,  1, 22, 88,
        90, 30, 44, 70, 64, 63, 92, 74])]

In [5]:
a_train, a_test = train_test_split(a)

In [6]:
a_test.shape, a_train.shape

((25,), (75,))

In [9]:
a_train , a_test = train_test_split(a, train_size=0.2, random_state=42)

In [10]:
a_train.shape, a_test.shape

((20,), (80,))

In [12]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [14]:
a_train, a_test, b_train, b_test = train_test_split(a, b, train_size=0.2, random_state=42)


In [15]:
b_train.shape, b_test.shape

((20,), (80,))